# Generated by Django 6.0.5 on 2026-05-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_deletedemployee_employee_designation_employee_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletedemployee',
            name='phone',
            field=models.CharField(default='0000000000', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(default='0000000000', max_length=15),
            preserve_default=False,
        ),
    ]
