# Generated by Django 6.0.5 on 2026-05-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_conversation_employeeprofile_message_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='profile_picture',
            field=models.TextField(blank=True, null=True),
        ),
    ]
