# Generated by Django 6.0.5 on 2026-05-22 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employeeprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='custom_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='status_emoji',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
