# Generated by Django 6.0.5 on 2026-05-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('designation', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.CharField(default='Developer', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(default=25000),
            preserve_default=False,
        ),
    ]
